PaGlobal_PetList_All = {
  _ui = {
    stc_TitleBG = nil,
    stc_InsideBG = nil,
    stc_Line = nil,
    stc_SkillInfoBG = nil,
    txt_SkillListDesc = nil,
    txt_LeaderSkillListTitle = nil,
    txt_LeaderSkillList = nil,
    txt_BaseSkillTitle = nil,
    txt_BaseSkill = nil,
    txt_SkillListTitle = nil,
    txt_SkillList = nil,
    txt_TierSetListTitle = nil,
    txt_TierSetList = nil,
    list2_Pet = nil,
    stc_FeedingBG = nil,
    stc_FeedingIconSlot = nil,
    stc_SelectedFeedingItemIcon = nil,
    _petLeader = {
      bg = nil,
      unsealBg = nil,
      iconBg = nil,
      gradeLine = nil,
      icon = nil,
      gradeMark = nil,
      name = nil,
      level = nil,
      tier = nil,
      hungryBg = nil,
      hungryProgress = nil,
      txt_HungryPercent = nil,
      hungryIcon = nil,
      btnFeed = nil,
      btnInfo = nil,
      btnSeal = nil,
      property = nil,
      orderFollow = nil,
      orderWait = nil,
      orderFind = nil,
      orderGetItem = nil,
      orderPlay = nil,
      orderPlayIcon = nil,
      skillIcon = {}
    }
  },
  _ui_pc = {
    chk_Popup = nil,
    btn_Question = nil,
    btn_Close = nil,
    stc_DesBG = nil,
    txt_DesL = nil,
    txt_DesR = nil,
    txt_Des = nil,
    stc_FindGroupBG = nil,
    _btn_AllSeal_Group = {},
    btn_ResetGroup = nil,
    stc_BtnGroup = nil,
    btn_Exchange = nil,
    btn_AllFeeding = nil,
    btn_AllSeal = nil,
    btn_Market = nil,
    btn_Feeding_FeedOne = nil,
    btn_Feeding_FeedFull = nil,
    btn_Feeding_Close = nil,
    stc_FilterBG = nil,
    rdo_All = nil,
    rdo_Normal = nil,
    rdo_PCRoom = nil,
    btn_RegistPCRoom = nil,
    btn_Guide = nil
  },
  _ui_console = {
    stc_Feeding_KeyGuideBG = nil,
    stc_Feeding_KeyGuideA = nil,
    stc_Feeding_KeyGuideX = nil,
    stc_Feeding_KeyGuideB = nil,
    stc_PopupBG = nil,
    rdo_Unseals = {
      feed = nil,
      order = nil,
      info = nil,
      seal = nil
    },
    rdo_Seals = {
      unseal = nil,
      exchange = nil,
      leader = nil,
      grouping = nil
    },
    stc_Popup_KeyGuideA = nil,
    stc_Bottom_KeyGuideBG = nil,
    stc_Bottom_KeyGuideA = nil,
    stc_Bottom_KeyGuideB = nil,
    stc_Bottom_KeyGuideX = nil,
    stc_Bottom_KeyGuideY = nil,
    stc_Bottom_KeyGuideRSHori = nil,
    stc_Bottom_KeyGuideRSClick = nil,
    stc_Bottom_KeyGuideLTPressRSClick = nil,
    petGroupingBtnList = {},
    _btn_AllSealConsole = {}
  },
  _GroupCount = 5,
  _isPlayOpen = false,
  _maxUnsealCount = nil,
  _isPremiumPcRoom = false,
  _gradeColorConfig = {
    [0] = Defines.Color.C_FFEFEFEF,
    [1] = Defines.Color.C_FFB5FF6D,
    [2] = Defines.Color.C_FF008AFF,
    [3] = Defines.Color.C_FFFFCE22,
    [4] = Defines.Color.C_FFD05D48
  },
  _petRaceCount = {
    [1] = "ê³ ì–‘ì´",
    [2] = "ê°œ",
    [3] = "ë§¤",
    [4] = "í­ê·„",
    [5] = "ì‚¬ë§‰ì—¬ìš°",
    [6] = "ê³ ìŠ´ë„ì¹˜",
    [7] = "ëˆˆì‚¬ëŒ",
    [8] = "ê³ ìŠ´ë„ì¹˜",
    [9] = "ì˜¤ëª©ëˆˆì´",
    [10] = "ë ›ì„œíŒ¬ë”",
    [11] = "ì•µë¬´ìƒˆ",
    [12] = "ë¶ê·¹ê³°",
    [13] = "ëŒë§¨ê²Œ",
    [14] = "ì´ë²¤íŠ¸í• ë¡œìœˆ1",
    [15] = "ì´ë²¤íŠ¸í• ë¡œìœˆ2",
    [16] = "ì´ë²¤íŠ¸í• ë¡œìœˆ3",
    [17] = "ì´ë²¤íŠ¸í• ë¡œìœˆ4",
    [18] = "ì´ë²¤íŠ¸í• ë¡œìœˆ5",
    [19] = "ì´ë²¤íŠ¸í• ë¡œìœˆ6",
    [20] = "ì–´ë¦° ì–‘",
    [22] = "ê¹Œë§ˆê·€",
    [23] = "ëª¬ìŠ¤í„°í« ì„ì‹œ",
    [24] = "ë§ˆë©‹",
    [25] = "ì—ì–´ë¦¬ìŠ¤",
    [26] = "ë£¨ëŒí”„",
    [27] = "ë¶‰ì€ì˜¤í¬",
    [28] = "ê³¨ë ˜",
    [29] = "ë‚˜ë¬´ ì •ë ¹",
    [30] = "í‚¤ë©”ë¼",
    [31] = "ì¼„íƒ€ìš°ë¡œìŠ¤",
    [32] = "ì¹´ë§ˆì‹¤ë¹„ì•„ ë¶ˆê³°",
    [33] = "ì•„ë¬´ê±°ë‚˜11",
    [34] = "ì•„ë¬´ê±°ë‚˜12",
    [35] = "ì•„ë¬´ê±°ë‚˜13",
    [36] = "ì•„ë¬´ê±°ë‚˜14",
    [37] = "ì•„ë¬´ê±°ë‚˜15",
    [38] = "ì•„ë¬´ê±°ë‚˜16",
    [39] = "ì•„ë¬´ê±°ë‚˜17",
    [40] = "ì•„ë¬´ê±°ë‚˜18",
    [41] = "ì•„ë¬´ê±°ë‚˜19",
    [42] = "ì•„ë¬´ê±°ë‚˜20",
    [43] = "ì•„ë¬´ê±°ë‚˜21",
    [44] = "ì•„ë¬´ê±°ë‚˜22",
    [45] = "ì•„ë¬´ê±°ë‚˜23",
    [46] = "ì•„ë¬´ê±°ë‚˜24",
    [47] = "ì•„ë¬´ê±°ë‚˜25",
    [48] = "ì•„ë¬´ê±°ë‚˜26",
    [49] = "ì•„ë¬´ê±°ë‚˜27",
    [50] = "ì•„ë¬´ê±°ë‚˜28",
    [51] = "ì•„ë¬´ê±°ë‚˜29",
    [52] = "ì•„ë¬´ê±°ë‚˜30",
    [53] = "ì•„ë¬´ê±°ë‚˜31",
    [54] = "ì•„ë¬´ê±°ë‚˜32",
    [55] = "ì•„ë¬´ê±°ë‚˜33",
    [56] = "ì•„ë¬´ê±°ë‚˜34",
    [57] = "ì•„ë¬´ê±°ë‚˜35",
    [58] = "ì•„ë¬´ê±°ë‚˜36",
    [59] = "ì•„ë¬´ê±°ë‚˜37",
    [60] = "ì•„ë¬´ê±°ë‚˜38",
    [61] = "ì•„ë¬´ê±°ë‚˜39",
    [62] = "ì•„ë¬´ê±°ë‚˜40",
    [63] = "ì•„ë¬´ê±°ë‚˜41",
    [64] = "ì•„ë¬´ê±°ë‚˜42",
    [65] = "ì•„ë¬´ê±°ë‚˜43",
    [66] = "ì•„ë¬´ê±°ë‚˜44",
    [67] = "ì•„ë¬´ê±°ë‚˜45",
    [68] = "ì•„ë¬´ê±°ë‚˜46",
    [69] = "ì•„ë¬´ê±°ë‚˜47",
    [70] = "ì•„ë¬´ê±°ë‚˜48",
    [71] = "ì•„ë¬´ê±°ë‚˜49",
    [72] = "ì•„ë¬´ê±°ë‚˜50",
    [73] = "ì•„ë¬´ê±°ë‚˜51",
    [74] = "ì•„ë¬´ê±°ë‚˜52",
    [75] = "ì•„ë¬´ê±°ë‚˜53",
    [76] = "ì•„ë¬´ê±°ë‚˜54",
    [77] = "ì•„ë¬´ê±°ë‚˜55",
    [78] = "ì•„ë¬´ê±°ë‚˜56",
    [79] = "ì•„ë¬´ê±°ë‚˜57",
    [80] = "ì•„ë¬´ê±°ë‚˜58",
    [81] = "ì•„ë¬´ê±°ë‚˜59",
    [82] = "ì•„ë¬´ê±°ë‚˜60",
    [83] = "ì•„ë¬´ê±°ë‚˜61",
    [84] = "ì•„ë¬´ê±°ë‚˜62",
    [85] = "ì•„ë¬´ê±°ë‚˜63",
    [86] = "ì•„ë¬´ê±°ë‚˜64",
    [87] = "ì•„ë¬´ê±°ë‚˜65",
    [88] = "ì•„ë¬´ê±°ë‚˜66",
    [89] = "ì•„ë¬´ê±°ë‚˜67",
    [90] = "ì•„ë¬´ê±°ë‚˜68",
    [91] = "ì•„ë¬´ê±°ë‚˜69",
    [92] = "ì•„ë¬´ê±°ë‚˜70",
    [93] = "ì•„ë¬´ê±°ë‚˜71",
    [94] = "ì•„ë¬´ê±°ë‚˜72",
    [95] = "ì•„ë¬´ê±°ë‚˜73",
    [96] = "ì•„ë¬´ê±°ë‚˜74",
    [97] = "ì•„ë¬´ê±°ë‚˜75",
    [98] = "ì•„ë¬´ê±°ë‚˜76",
    [99] = "í•©ì„±ìš© í«"
  },
  _isPetFlyPet = {
    [1] = 3,
    [2] = 9,
    [3] = 11,
    [4] = 15
  },
  _checkUnSealGroupList = {
    [1] = {},
    [2] = {},
    [3] = {},
    [4] = {},
    [5] = {}
  },
  _checkUnSealList = {},
  _SealDATACount = 0,
  _UnSealDataCount = 0,
  _petOrderList = {
    _follow = {},
    _find = {},
    _getItem = {}
  },
  _nowSelectGroup = 0,
  _feedingPetIndex = 0,
  _feedStaticItemCount = ToClient_Pet_GetFeedStaticItemCount() * 2,
  _cachedUserFeedItemCount = 0,
  _feedSlot = {},
  _feedAllSlot = {},
  _slotConfig = {
    createBorder = true,
    createCount = true,
    createFamilyInvenotry = true
  },
  _selectItemIndex = -1,
  _selectSlotBg = nil,
  _selectAllSlotBg = nil,
  _maxskillTypeCount = 21,
  _skillTypeString = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_0"),
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_1"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_2"),
    [3] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_3"),
    [4] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_4"),
    [5] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_5"),
    [6] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_6"),
    [7] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_7"),
    [8] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_8"),
    [9] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_9"),
    [10] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_10"),
    [11] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_11"),
    [12] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_12"),
    [13] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_13"),
    [14] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_14"),
    [15] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_15"),
    [16] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_16"),
    [17] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_17"),
    [18] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_18"),
    [19] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_19"),
    [20] = PAGetString(Defines.StringSheet_GAME, "LUA_PETSKILLTYPE_20")
  },
  _gradeTypeUV = {
    [0] = {
      193,
      332,
      275,
      350
    },
    [1] = {
      193,
      313,
      275,
      331
    },
    [2] = {
      133,
      351,
      215,
      369
    },
    [3] = {
      110,
      332,
      192,
      350
    },
    [4] = {
      110,
      313,
      192,
      331
    },
    [5] = {
      110,
      313,
      192,
      331
    }
  },
  _plusPoint = {
    [0] = 7,
    [1] = 5,
    [2] = 5,
    [4] = 4,
    [5] = 20
  },
  _skillInfo = {
    plusCount = {},
    skillTypeCount = {}
  },
  _baseSkillTypeString = {
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE1"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE2"),
    [3] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE3"),
    [4] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE4"),
    [5] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE5"),
    [6] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE6"),
    [7] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE7"),
    [8] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE8"),
    [9] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE9"),
    [10] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE10"),
    [11] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE11"),
    [12] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE12"),
    [13] = "",
    [14] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE14"),
    [15] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE15"),
    [16] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE16"),
    [17] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE17"),
    [18] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE18"),
    [19] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPE19")
  },
  _baseSkillTypeUnit = {
    [1] = "",
    [2] = "",
    [3] = "%",
    [4] = "%",
    [5] = "%",
    [6] = "%",
    [7] = "%",
    [8] = "%",
    [9] = "%",
    [10] = "%",
    [11] = PAGetString(Defines.StringSheet_GAME, "LUA_PETLIST_BASESKILLTYPEUNIT_SECOND"),
    [12] = PAGetString(Defines.StringSheet_RESOURCE, "TRADEMARKET_STD_TXT_LT"),
    [13] = "%",
    [14] = "%",
    [15] = "%",
    [16] = "%",
    [17] = "%",
    [18] = "%",
    [19] = PAGetString(Defines.StringSheet_RESOURCE, "TRADEMARKET_STD_TXT_LT")
  },
  _baseSkillMultiplePoint = {
    [1] = 25,
    [2] = 10,
    [3] = 1,
    [4] = 1,
    [5] = 1,
    [6] = 1,
    [7] = 1,
    [8] = 1,
    [9] = 5,
    [10] = 1,
    [11] = 5,
    [12] = 10,
    [13] = 5,
    [14] = 1,
    [15] = 1,
    [16] = 1,
    [17] = 1,
    [18] = 1,
    [19] = 50
  },
  _tipType = {
    ResetGroup = 0,
    GroupSelect_first = 1,
    GroupSelect_second = 2,
    GroupSelect_third = 3,
    GroupSelect_fourth = 4,
    GroupSelect_fifth = 5,
    Exchange = 6,
    AllSeal = 7,
    UpdateGuide = 8
  },
  _leaderPetTier = 5,
  _showLeaderEffect = false,
  _originListSpanSizeY = 0,
  _originListSizeY = 0,
  _originSkillPosY = 0,
  _isFeedToAll = false,
  _contentsSkillIconCount = 4,
  _currentPetNo64 = nil,
  _popUpKeyGuideADefaultPosY = nil,
  _popUpKeyGuideAGapSizeY = nil,
  _keyGuideAlignType = {
    none = 0,
    basic = 1,
    popup = 2,
    feedOne = 3,
    feedAll = 4
  },
  _originPanelSizeY = 0,
  _originInsideBGSizeY = 0,
  _originPetListSpanY = 0,
  _originDesBGSpanY = 0,
  _originFindGroupBGSpanY = 0,
  _originBtnGroupSpanY = 0,
  _originSkillInfoBGSpanY = 0,
  _originBtnRegistPCRoomSpanY = 0,
  _originLeaderPetSpanY = 0,
  _isUnsealLeaderPet = false,
  _petLeaderNo = nil,
  _isConsole = nil,
  _pcFilterInitialize = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/PetInfo/Panel_Window_PetList_All_1.lua")
runLua("UI_Data/Script/Window/PetInfo/Panel_Window_PetList_All_2.lua")
runLua("UI_Data/Script/Window/PetInfo/Panel_Window_PetList_All_3.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_PetList_All_Init")
function FromClient_PetList_All_Init()
  PaGlobal_PetList_All:initialize()
end
